# Site
name: "SciTECH"
title: "SciTECH"
description: "Science & Tech News at Choate Rosemary Hall."
meta_description: "Science & Tech News at Choate Rosemary Hall."
logo: 'assets/images/logo' # Make sure this logo is also in .jp2 and .webp formats
favicon: 'assets/images/logo'
baseurl: 
google_analytics:
disqus: 'choate-scitech'
mailchimp-list: 'https://github.us20.list-manage.com/subscribe?u=e5ce6a759c37aae6c0b9a13f7&id=95aa49abe2'
include: ["_pages"]
exclude: ["hooks", "Gemfile", "Gemfile.lock", "README.md", "deploy", "serve", "package.json", "docs/", "docs-temp/", "*.py", "*.pickle"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-git_metadata

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
